### ISSUE TITLE
Implement url shortening.

### ISSUE THREAD

**Issue by aryan9600** [IEEE-VIT/flask.ly#1]
**Please describe the feature you want this project to offer**
It would be nice if this project had logic to generate shortened urls of preferred urls.

**Describe the solution you'd like**
Use a hashing algorithm in `shorten()` and store the hash and the actual url in the database.

**Describe alternatives you've considered (Optional)**

**Additional context (Optional)**

**Comment by andrewmiko** [comment]
@ShubhamPalriwala will take this one! :)

**Comment by ShubhamPalriwala** [comment]
Sure @andrewmiko !

**Comment by andrewmiko** [comment]
@ShubhamPalriwala please assign issue to me. Will work on it after #11 merge.

**Comment by andrewmiko** [comment]
Hello, please verify #13 PR. Thanks.
