### ISSUE TITLE
Implement quick url shortening

### ISSUE THREAD

**Issue by ShubhamPalriwala** [IEEE-VIT/flask.ly#2]
**Please describe the feature you want this project to offer**
It would be nice if this project had logic to generate shortened urls of preferred urls quickly.

**Describe the solution you'd like**
In the `quickShorten()` use the dictionary and add the given url as a value and use the key as the shortened url.

**Describe alternatives you've considered (Optional)**

**Additional context (Optional)**

**Comment by divyanshsikarwar** [comment]
i want to work on this,
but where in the repo i have to add my file ?

**Comment by ShubhamPalriwala** [comment]
You can find the `quickShorten()` in the routes.py file in routes directory [here](https://github.com/IEEE-VIT/flask.ly/blob/master/routes/routes.py).

**Comment by ShubhamPalriwala** [comment]
Done PR #10
