### ISSUE TITLE
Implement the redirection to actual url

### ISSUE THREAD

**Issue by ShubhamPalriwala** [IEEE-VIT/flask.ly#7]
**Please describe the feature you want this project to offer**
The shortened url should redirect to the actual url

**Describe the solution you'd like**
In the `redirectToActualURL()`, the user enters the shortened url, map it from the database and redirect them to their actual url

**Describe alternatives you've considered (Optional)**

**Additional context (Optional)**

**Comment by sudonims** [comment]
I have implemented the feature...Its in the PR ..You can check #10
