### ISSUE TITLE
Implement the Url model

### ISSUE THREAD

**Issue by ShubhamPalriwala** [IEEE-VIT/flask.ly#9]
**Please describe the feature you want this project to offer**
We should have a Url database model which can store the urls and their corresponding custom urls

**Describe the solution you'd like**
In the `Url` class, define the database model in such a way that it stores the custom url as well as the actual url entered by the user.

**Describe alternatives you've considered (Optional)**

**Additional context (Optional)**

**Comment by andrewmiko** [comment]
@ShubhamPalriwala I can work on URL model.

**Comment by ShubhamPalriwala** [comment]
Great @andrewmiko ! Go for it !

**Comment by andrewmiko** [comment]
@ShubhamPalriwala will do it later today.

**Comment by andrewmiko** [comment]
@ShubhamPalriwala can you please assign issue on me? Thanks.

**Comment by andrewmiko** [comment]
@ShubhamPalriwala I have several questions regarding this feature.

1. What database do you plan to use: SQLite, MySQL or PostgreSQL?
2. What database ORM system is preferable? Peewee or SQLAlchemy?

**Comment by ShubhamPalriwala** [comment]
Please Use SQLite along with SQLAlchemy !

**Comment by andrewmiko** [comment]
Pull-request #11
